### ISSUE TITLE
[SUGGESTION] Show how to implement BeastCSS with ExpressJS

### ISSUE THREAD

**Issue by YPCrumble** [freddy38510/beastcss#66]
Hi - first, thank you for building this! It seems to be the best CSS parser out there currently. 

I would love to use it as part of my Express server as a middleware to adjust the CSS on the page on the fly (if BeastCSS ends up being performant enough!). My issue is that I can't figure out how to make it work with ExpressJS using the async example in the docs. A really helpful feature would either be a middleware export for Express or perhaps just showing how that would work with Express in the documentation.

The issue was that even if I made the wrapping express function async I couldn't get it to properly handle my CSS. It was a while back when I tried but if you need more of a code example I'm happy to provide what I tried and didn't work!

**Comment by freddy38510** [comment]
Hello,

Thank, I really appreciate that, but all credit goes to [leeoniya](https://github.com/leeoniya ) for the speed of the [CSS/html parsers](https://github.com/leeoniya/dropcss).

It's an interesting use case. If you can provide an example I could help you with pleasure!

**Comment by freddy38510** [comment]
After some digging, it depends on many things to achieve what you want.

You need the html string and the absolute path of the directory containing your assets.

How do you generate your html ?
From a static file ? From a template with [res.render](http://expressjs.com/en/4x/api.html#res.render) ?

Once you have access to the html string, you can try to run beastcss on it. If you got some messages like `unable to locate stylesheet: url/to/the/stylesheet.css` you need to tweak the beastcss option `path`.

There is [an example on codesandbox](https://codesandbox.io/s/express-beastcss-demo-forked-h81z45?file=/routes/index.js) using [template engines](http://expressjs.com/en/guide/using-template-engines.html) with Express.

**Comment by YPCrumble** [comment]
@freddy38510 thank you for this! It was super helpful and works well.

One question I have is, do you think this is a good idea, or is there a more performant way to use BeastCSS on pages that aren't static pages that I can run the code on one time only?

Currently what I'm doing is using BeastCSS as an Express middleware on my site per your example, but only for cached pages. For these cached pages, it removes the CSS in, say, 200ms, one time, and then for every subsequent request I get a page load that has ~5-10kb less CSS, as well as any below the fold CSS is now non-blocking. So for a cached page this makes sense, but if I had to run this 200ms for every request it likely wouldn't make sense.

I'm not sure whether this was the way the library was intended to be used, but I'm curious whether this seems like a good use case or not, or whether there's a better approach to the underlying problem that my CSS files of ~20-25kb all have roughly ~5-10kb of unused css, as well as a lot of below the fold CSS that can be loaded asynchronously.

Thanks again for building and sharing this library!

**Comment by freddy38510** [comment]
Thank you for your feedbacks, I really appreciate it.

Initially, I developed this library for use with a static site generator.
But it can be used with any build tool, as long as you have access to all the html pages you want to process.

Is it possible for you to do it outside Express.js when you're building your application ?

Note 1: Subsequent executions of the library `process` method should be faster than the first one.

Note 2: There is no concept of "below the fold" with this library. All the html elements are processed to avoid massive recalculation and repainting costs once the non-critical css is loaded.

**Comment by YPCrumble** [comment]
Thank you for your response! I believe my issue is that I'm using server-side rendering, where I have a dynamically generated HTML file. There isn't really a place for BeastCSS to inline anything (e.g., using the webpack plugin) until the final HTML has been rendered. I could be wrong but that's my current understanding.

One question - in terms of "non-critical css" - how is this determined in this library if it isn't looking for "below the fold" content and inlining CSS that is above the fold, and loading other CSS asynchronously.

Is there a library this is running that does that or a particular part of the code I could take a look at?

Thanks again for building this and your helpful responses! Once I have my implementation up and running I'd like to try to add a documentation PR so that anyone with the same questions can find them there.

**Comment by freddy38510** [comment]
Yeah, in your case there is no better place than an Express.js middleware. The best case scenario for performance would be to pre-render (with SSR) all pages at built-time. Which would effectively lead to the generation of a static site (SSG).

The library looks for internal and/or external stylesheets in the html string. Internal refers to `<style>` tags and external  to `<link rel="stylesheet" href="style.css">` tags.

The critical css _("used css" would be more appropriate)_ is then extracted using the [`dropcss`](https://github.com/freddy38510/dropcss/) library. You can take a look if you want to better understand how css and html are parsed.

Finally, the used css is injected into the html string in a `<style>` tag. If the css comes from an external stylesheet, the corresponding `<link>` tag is modified to load the external stylesheet asynchronously using the [loadCSS technique](https://www.filamentgroup.com/lab/load-css-simpler/). This way the external stylesheet is no longer a render-blocking resource.

> Once I have my implementation up and running I'd like to try to add a documentation PR so that anyone with the same questions can find them there.

All PRs are welcome, especially for the documentation which is actually very brief.

**Comment by YPCrumble** [comment]
Thanks again! It seems that there's one drawback to this method of using Express middleware, in that I can't really call `await beastcss.pruneSources();` because if certain (non-cached) pages are called, the required CSS wouldn't be present.

An interesting workaround would be to create _new_ files via the `pruneSources` method rather than pruning existing files. I could see making an option on `updateExternalStyleSheet` to create a new file rather than overwriting the existing file - perhaps appending `-beastcss.css` or something like that. 

Similarly, it would need to avoid calling the `removeExternalStylesheet` method that removes existing CSS if the CSS was no longer necessary.

Part of me wonders whether that would be a better implementation overall. If the stylesheet isn't present in the HTML it doesn't really matter whether that file is still available or not in the filesystem - it won't be sent to the client. Keeping the original and having BeastCSS create new versions instead would allow me to use either the pruned file or the original depending on whether I'm serving the CSS to a logged out user (for which I use the cached page that applies BeastCSS) or a logged-in user (for whom I would like to serve the regular CSS), as well as allow for comparing the two after the build to diagnose any potential issues.

**Comment by freddy38510** [comment]
I wonder what is the performance gain of pruning the sources. Also consider that having multiple pruned external stylesheets reduces the interest of in-browser caching. Additionally, writing to filesystem will increase execution time.

About the implementation, I agree with you, maybe deleting/updating external stylesheets is too opinionated.
On the other hand, it is possible to override the `updateExternalStylesheet` and `removeExternalStylesheet` methods by extending the Beastcss class.

**Comment by YPCrumble** [comment]
> I wonder what is the performance gain of pruning the sources.

The reason I'm using the library is to try to better pass this audit for SEO: https://developer.chrome.com/docs/lighthouse/performance/unused-css-rules/?utm_source=lighthouse&utm_medium=lr

So what I'm thinking is that the `pruneSources` will reduce unused CSS and get me better SEO results. The thinking by Google is that for mobile devices with limited data and slow connections, reducing download size is a high priority.

Agree that it would reduce the interest of in-browser caching. My general sense is that Google de-prioritizes this for whatever reason for SEO purposes - perhaps because much of SEO is for new users?

> Additionally, writing to filesystem will increase execution time.

Would it actually increase execution time to write a new file vs. the current implementation that overwrites an existing file?

Thanks again for all your thoughtful responses!

**Comment by freddy38510** [comment]
External stylesheets are loaded asynchronously with low priority. Thus, the size of stylesheets should not affect the First Contentful Paint metric. But I guess reducing the size of async external stylesheets might improve performance after all.

The problem here is that with the `pruneSources` method, only the used css (which should be small) is removed from the external stylesheets. The library is unable to distinguish non-critical CSS rules from unused CSS rules.

That's why I was wondering if removing critical/used CSS from external stylesheets had negligible performance impact or not.

> Would it actually increase execution time to write a new file vs. the current implementation that overwrites an existing file?

No it won't, I confused your use case with the original usage of this library, which is to call the `pruneSources` method after all the html pages have been processed.

I was trying to implement a new option to suit your needs, but ran into a problem. What about hashing in filenames? I could just add a suffix or prefix to the original filenames, but if the filenames contain a hash for cache-busting, that makes it a bit complex. I should use Regexps to detect hash in filenames and generate new ones. It's too error-prone.

I'm thinking of another way to do it. Maybe let users define filenames or provide a pattern. What do you think ?

**Comment by YPCrumble** [comment]
Thanks for the ideas! On the hashing, at least for my use case, I'm not sure why that would matter. Webpack creates a new filename each time like: `some-file.[hash].chunk.css`.

The current implementation for BeastCSS simply adjusts `some-file.[hash].chunk.css`, and leaves the CSS `<link>` elements as-is.

What I'm suggesting is to do something like this:

1. Instead of overwriting `some-file.[hash].chunk.css`, create a new file like `some-file.[hash].chunk.beast.css`
2. In the HTML, change `some-file.[hash].chunk.css` to `some-file.[hash].chunk.beast.css` so that the HTML that has been processed by BeastCSS picks up the proper (pruned) CSS.

What do you think?

**Comment by freddy38510** [comment]
Webpack creates a hash based on the content of the asset. So the filename will be different between compilations if the content is different.

What if something changes in an html page ? The unused css generated by beastcss might be different than the one cached in the browser, but the filename would be the same if the original stylesheet filename didn't change. The browser will use the cached one instead of the new one.

**Comment by YPCrumble** [comment]
Hm - I'm trying to understand. Webpack changes the hash each time the HTML changes, i.e., every time I make a change to my codebase, I run webpack to generate a new bundle.

When I refer to using BeastCSS in a "cached version of the page" I'm referring to server-side caching, not client-side caching. I cache the entire HTML string so that I don't have to re-run any server-side rendering, i.e., compiling the JavaScript or calling third-party APIs. And the cache gets cleared every time I run a new webpack build, so there isn't a scenario in which a client is asking for an old string.

**Comment by freddy38510** [comment]
I'm not talking specifically about your use case. Regardless of the bundler used, if nothing changes in the stylesheet source code between compilations, the filename generated with the hash should be the same each time.

What I was trying to explain is that when the content of an html page changes; for example, you can add a new component to a page or remove one; so the unused css can be different even if the stylesheet stays exactly the same. In this case, beastcss would produce a different "pruned" stylesheet, but the filename would not change.

If the server asks the client to cache the stylesheet via its response headers, the client will load the cached stylesheet. This could result in duplicate CSS rules between the inlinded style and the external stylesheet, or even worse, missing rules.

Out of curiosity, don't you put a "Cache-Control" http header field in the responses you send to the client via express ? I mean, for static assets, like css or js.

**Comment by YPCrumble** [comment]
I see now - isn't what you're describing an issue for BeastCSS in its current implementation, not just if BeastCSS writes a new stylesheet each time, if the `pruneSources` method is invoked? Or am I missing something?

**Comment by freddy38510** [comment]
You're right, the same cache busting issue appears in all other scenarios.

Removing critical CSS from the external stylesheet will have little or no performance improvement. Especially for your use case since you will have one cached stylesheet per page instead of single one for the entire application.

Unless we find a better implementation to fix these issues, I recommend not using this method. I'm up for discussing it if you have any ideas.

**Comment by YPCrumble** [comment]
That makes a lot of sense! I'm going to think on it, but for now will close this issue as the original questions I had have been solved.

Thank you again for thinking through this!
